### ISSUE TITLE
supervisor issue

### ISSUE THREAD

**Issue by hadariyair** [gecche/laravel-multidomain#123]
Hi,

I"m running the following supervisor command 

`[program:laravel-worker-test1]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/aa/artisan queue:work --domain=aa1 --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=business
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/worker-test1.log
stopwaitsecs=3600`

and getting the error "The "--domain" option does not exist."

can you please assist?

Thanks,
Yair

**Comment by hadariyair** [comment]
In laravel.log I see the following error:
[2024-11-13 06:54:16] local.ERROR: The "--domain" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--domain\" option does not exist. at /var/www/esbinaa-business/vendor/symfony/console/Input/ArgvInput.php:223)
[stacktrace]
#0 /var/www/esbinaa-business/vendor/symfony/console/Input/ArgvInput.php(150): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption()
#1 /var/www/esbinaa-business/vendor/symfony/console/Input/ArgvInput.php(85): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption()
#2 /var/www/esbinaa-business/vendor/symfony/console/Input/ArgvInput.php(74): Symfony\\Component\\Console\\Input\\ArgvInput->parseToken()
#3 /var/www/esbinaa-business/vendor/symfony/console/Input/Input.php(56): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#4 /var/www/esbinaa-business/vendor/symfony/console/Command/Command.php(285): Symfony\\Component\\Console\\Input\\Input->bind()
#5 /var/www/esbinaa-business/vendor/symfony/console/Application.php(1078): Symfony\\Component\\Console\\Command\\Command->run()
#6 /var/www/esbinaa-business/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#7 /var/www/esbinaa-business/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#8 /var/www/esbinaa-business/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#9 /var/www/esbinaa-business/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#10 /var/www/esbinaa-business/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#11 {main}
"}

**Comment by hadariyair** [comment]
The problem was solved after updating Http/Kernel.php and Console/Kernel.php

Thanks again for contributing the plugin to the community

Yair
